/* INSERTY */

INSERT INTO ROLA (ROLA_ID, NAZWA) VALUES (2, 'WOLONTARIUSZ');
INSERT INTO ROLA (ROLA_ID, NAZWA) VALUES (1, 'REDAKTOR');
INSERT INTO ROLA (ROLA_ID, NAZWA) VALUES (3, 'TURYSTA');

INSERT INTO UZYTKOWNIK (LOGIN, HASLO, IMIE, NAZWISKO) VALUES ('dzasta94', '1234' , 'Justyna', 'Makowska');
INSERT INTO UZYTKOWNIK (LOGIN, HASLO, IMIE, NAZWISKO) VALUES ('arksad95', '12345' , 'Arkadiusz', 'Sadowski');
INSERT INTO UZYTKOWNIK (LOGIN, HASLO, IMIE, NAZWISKO) VALUES ('jendi94', '123456' , 'Jedrzej', 'Antkiewicz');
INSERT INTO UZYTKOWNIK (LOGIN, HASLO, IMIE, NAZWISKO) VALUES ('blan95', '123' , 'Blanka', 'Sznyter');

INSERT INTO ROLAUZYTKOWNIKA (UZYTOWNIK_ID, ROLA_ID) VALUES (1, 1);
INSERT INTO ROLAUZYTKOWNIKA (UZYTOWNIK_ID, ROLA_ID) VALUES (2, 1);
INSERT INTO ROLAUZYTKOWNIKA (UZYTOWNIK_ID, ROLA_ID) VALUES (2, 1);



INSERT INTO ADRES (ADrES_ID, ULICA, KOD, MIASTO, KRAJ) VALUES
                    (1, 'Dlugi Targ', '80-833', 'Gdañsk', 'Polska');
INSERT INTO WLASCICIEL (WLASCICIEL_ID, WLASCICIEL_NAZWA1, KONTAKT) VALUES(1, 'Narodowy Instytut Dziedzictwa','228261714' );
INSERT INTO WSPOLRZEDNE (WSPOLRZEDNE_ID, DLUGOSC, SZEROKOSC) VALUES (1, 54.348575, 18.653364);
INSERT INTO OBIEKT (NAZWA, FUNKCJA, ADRES_ID, WLASCICIEL_ID, DATA_POWSTANIA, WSPOLRZEDNE_ID) VALUES
                ('Fontanna Neptuna w Gdañsku', 'FONTANNA',  1,  1, '1633-01-01' ,1);